### ISSUE TITLE
Super variant?

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#15]
Sorry if I should know this, but what the heck is Super variant?
It was disabled previously, but enabled now. Nothing in the readme about it, and I don't remember ever seeing anything in the forums about it.

**Comment by Wiedmolol** [comment]
Well, we just got Super variant of Kryton - https://cosmosquest.net/wb.php?id=236
It basically means that boss gives double rewards but can only be attacked 1000 times instead 3k before it's dead and everyone can attack at most 2 times. Of course info about Super WBs is scarce because Gaia apparently doesn't like to inform players about new mechanics but to the best of our knowledge every boss has 10% chance to spawn as Super variant and on Wednesdays we will be probably getting a guaranteed SWB spawn.
