### ISSUE TITLE
v0.9.4 - lost lots of WB attacks :(

### ISSUE THREAD

**Issue by saynotoid** [Wiedmolol/CQAutomater#19]
http://prntscr.com/jnqqml
http://prntscr.com/jnqrfd
instead of a single attack when 4 are available i am left with a single unused and 4+ fired :(

if u can do smth about it pls... maybe some larger timers between attacks on the same boss or some extra clarification of owned/used etc atks
thx

p.s. btw can be related to ISP disconnects or however its called !!! please make some extra verification or whatever thx in advance:)

p.p.s need some super "root" rule to not overkill the "atks needed" amount (got from the game server or whatever, not counted from my PC fired) sry 4 bad eng.

p.p.p.s. (ok falling asleep) but last thing to mention: can be done via "dmg done" divided or ">=" some set value if can't get atks made to WB from the game server etc - whatever u prefer

**Comment by Wiedmolol** [comment]
First of all: do you have your username enabled on cosmosquest.net website? If not but you still enabled auto-wb regardless of the warning this is basically what will happen.  

I don't want to deploy new version before testing but I've changed the code a bit - now new attacks shouldn't be added to queue if attacks are already in the queue so that should prevent attacking WB too many times when you have connection problems.

**Comment by saynotoid** [comment]
yes ofc ive enabled it, and the claimer was runnin kinda smooth for a few days until connection problems. thx ill try the next version.
